import React from 'react';
import useDocumentTitle from '../../hooks/useDocumentTitle';
import useMetaDescription from '../../hooks/useMetaDescription';

const TermsConditions = () => {
  useDocumentTitle('Terms | Blubridge');
  useMetaDescription('Read the Terms of Use governing access to Blubridge Technologies websites, APIs, research tools, and AI services.');

  const headingStyle = {
    fontSize: '20px',
    fontWeight: '600',
    color: '#0B1F3B',
    marginBottom: '16px',
    marginTop: '32px'
  };

  const paragraphStyle = {
    fontSize: '15px',
    color: '#4a5568',
    lineHeight: '1.8',
    marginBottom: '16px',
    textAlign: 'justify'
  };

  return (
    <div 
      style={{
        minHeight: '100vh',
        backgroundColor: '#F1F2FA',
        paddingTop: '80px',
        paddingBottom: '80px'
      }}
    >
      <div style={{
        maxWidth: '1261px',
        margin: '0 auto',
        padding: '0 24px'
      }}>
        {/* Main Card */}
        <div style={{
          backgroundColor: '#FFFFFF',
          borderRadius: '20px',
          padding: '60px',
          boxShadow: '0 4px 24px rgba(0, 0, 0, 0.06)'
        }}>
          {/* Page Title */}
          <h1 style={{
            fontSize: '36px',
            fontWeight: '600',
            color: '#0B1F3B',
            marginBottom: '8px',
            letterSpacing: '-0.02em'
          }}>
            Terms of Use
          </h1>

          <p style={{
            fontSize: '18px',
            fontWeight: '500',
            color: '#0B1F3B',
            marginBottom: '8px'
          }}>
            Blubridge Technologies Private Limited
          </p>

          <p style={{
            fontSize: '14px',
            color: '#6b7280',
            marginBottom: '32px'
          }}>
            Last Updated on : 23rd January 2026
          </p>

          {/* Introduction */}
          <p style={paragraphStyle}>
            These Terms of Use ("Terms") set out the legally binding agreement between you ("you" or "User") and Blubridge Technologies Private Limited ("Blubridge", "we", "our" or "us") for access to and use of our websites, applications, developer interfaces, application programming interfaces, research previews, documentation, datasets or evaluation tools that we make available, and any related services, features or support channels (collectively, the "Services"). These Terms apply whether you create an account, use a trial, access a beta, or otherwise interact with the Services.
          </p>

          <p style={paragraphStyle}>
            By clicking an acceptance button, by creating an account, or by accessing or using any part of the Services, you confirm that you have read and understood these Terms and agree to be bound by them. If you do not agree, you must not access or use the Services. Where you use the Services on behalf of an entity, you represent and warrant that you have authority to bind that entity, and the terms "you" and "your" will refer to that entity.
          </p>

          <p style={paragraphStyle}>
            These Terms are an electronic record under the Information Technology Act, 2000 and the rules made thereunder, and are published in accordance with applicable intermediary and digital media rules in India, as amended from time to time. This electronic record is generated by a computer system and does not require physical or digital signatures.
          </p>

          {/* Section 1 */}
          <h2 style={headingStyle}>1. Parts of this Agreement</h2>
          <p style={paragraphStyle}>
            These Terms include the general terms in this document together with any additional terms that apply to specific products, APIs, research previews, evaluation programs, or other features that you choose to use ("Service Specific Terms"). Service Specific Terms may be presented at sign-up, in a product console, in a developer portal, or in a separate document. If Service Specific Terms conflict with these general Terms, the Service Specific Terms will prevail for that specific Service, and the remaining provisions of these Terms will continue to apply.
          </p>
          <p style={paragraphStyle}>
            Where we provide policies that are referenced by these Terms, including our Privacy Policy and any acceptable use or security guidance, those policies are incorporated by reference and form part of the agreement between you and us. If you do not agree to an incorporated policy, you must not use the Services.
          </p>

          {/* Section 2 */}
          <h2 style={headingStyle}>2. Eligibility and permitted users</h2>
          <p style={paragraphStyle}>
            You may use the Services only if you are legally capable of entering into a binding contract under applicable laws. If you are using the Services on behalf of a company, partnership, trust, government body, educational institution, or other organization, you must be duly authorized to accept these Terms and to use the Services on its behalf. You agree to provide evidence of such authority if we reasonably request it.
          </p>
          <p style={paragraphStyle}>
            If you are under 18 years of age, you may use the Services only under the supervision and guidance of a parent or legal guardian who accepts these Terms on your behalf. We may restrict access to certain Services, including developer features, paid plans, or research previews, based on age or other eligibility criteria.
          </p>

          {/* Section 3 */}
          <h2 style={headingStyle}>3. Description of the Services</h2>
          <p style={paragraphStyle}>
            Blubridge is an AI research and engineering company based in India. We may offer research-led services such as model evaluation environments, prototype APIs, fine-tuning or customization workflows, safety tooling, developer utilities, and documentation. Some Services may provide outputs generated by automated systems. The Services may evolve rapidly because they are informed by ongoing research and experimentation.
          </p>
          <p style={paragraphStyle}>
            We may provide the Services through a web interface, software development kits, APIs, command line tools, or other integrations. You are responsible for obtaining and maintaining compatible devices, browsers, and internet connectivity. We may change, suspend, or discontinue any part of the Services at any time as described further in these Terms.
          </p>

          {/* Section 4 */}
          <h2 style={headingStyle}>4. Account registration, access, and security</h2>
          <p style={paragraphStyle}>
            To access certain Services, you may need to register for an account and provide information such as your legal name, organization name, email address, billing details, and other information necessary to enable the Service. You agree that all information you provide will be accurate, complete, and kept up to date. We are not required to verify your identity, but we may do so to protect the integrity and security of the Services, to comply with law, or to prevent misuse.
          </p>
          <p style={paragraphStyle}>
            You are responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account, including the actions of any users who access the Services through your account or organization workspace. You must promptly notify us of any suspected unauthorized access or security incident involving your account.
          </p>
          <p style={paragraphStyle}>
            We may disable or suspend access credentials if we reasonably believe you have violated these Terms, if your account presents a security risk, or if required by law. You agree to respond promptly to communications from us regarding account security, compliance, complaints, or abuse reports.
          </p>

          {/* Section 5 */}
          <h2 style={headingStyle}>5. Beta services, previews, and free trials</h2>
          <p style={paragraphStyle}>
            We may make certain features available as alpha, beta, pilot, research preview, or early access services (collectively, "Beta Services"). Beta Services are provided for testing and evaluation. They may be unstable, may change without notice, and may be discontinued at any time. We may set limits on usage, retention, support, or availability for Beta Services.
          </p>
          <p style={paragraphStyle}>
            If you register for a free trial or limited evaluation of a paid Service, the trial will run until the earlier of the end of the trial period, the start of a paid subscription, or termination by you or by us. During trials and Beta Services, the Service may be provided as-is, without warranties, service commitments, or support obligations to the maximum extent permitted by law. You are responsible for exporting any data or Content you wish to retain before a trial ends, because access or data may be reduced or removed after the trial concludes.
          </p>

          {/* Section 6 */}
          <h2 style={headingStyle}>6. Fees, taxes, invoicing, and payment processing</h2>
          <p style={paragraphStyle}>
            Some Services may require payment of subscription fees, usage-based fees, or other charges (collectively, "Fees"). Where Fees apply, the price and billing terms will be described at the time you subscribe, in your order form, or in the Service console. Unless otherwise stated, Fees are payable in advance and are non-refundable except where required by applicable law or where an order form expressly provides otherwise.
          </p>
          <p style={paragraphStyle}>
            We may use third-party payment processors to handle payments. You authorize us and our payment processors to charge your selected payment method for Fees, applicable taxes, and any authorized renewals. You agree not to use a payment method that you are not authorized to use. If a payment fails, we may suspend access to the relevant Service until payment is received.
          </p>
          <p style={paragraphStyle}>
            Where applicable, taxes such as GST, VAT, sales tax, or similar charges may be added to invoices according to the laws of the relevant jurisdiction. If you provide valid tax registration details and required documentation, we will reflect it on invoices as permitted by law. You are responsible for any taxes, duties, or levies that apply to your purchase or use of the Services, except for taxes on our income.
          </p>

          {/* Section 7 */}
          <h2 style={headingStyle}>7. Cancellation, renewal, and plan changes</h2>
          <p style={paragraphStyle}>
            If your subscription renews automatically, it will renew at the end of each billing period unless you cancel, downgrade to a free plan, or disable auto-renewal in the manner provided by the Service. You are responsible for cancelling before the renewal date if you do not wish to renew. Where we make significant price changes that apply to your plan, we will use commercially reasonable efforts to provide advance notice and apply the change at the next renewal unless law requires a different approach.
          </p>
          <p style={paragraphStyle}>
            If you cancel a paid subscription, you will generally continue to have access to the paid features until the end of your current billing period, and no further charges will be applied unless you re-subscribe. Fees already paid for the current period are not refundable, and unused portions of the billing period are not credited, except where required by law or an order form provides otherwise.
          </p>

          {/* Section 8 */}
          <h2 style={headingStyle}>8. Ownership and intellectual property</h2>
          <p style={paragraphStyle}>
            The Services, including the underlying software, models, training or evaluation methodologies, process flows, datasets we create, documentation, designs, interfaces, algorithms, technical know-how, and all related intellectual property, are owned by Blubridge or its licensors. Nothing in these Terms transfers ownership of our intellectual property to you.
          </p>
          <p style={paragraphStyle}>
            Subject to your compliance with these Terms and any applicable Service Specific Terms, we grant you a limited, non-exclusive, non-transferable, revocable right to access and use the Services for your internal business purposes or personal use, as applicable. You must not copy, modify, distribute, sell, lease, sublicense, or create derivative works from the Services, nor may you reverse engineer, decompile, or attempt to discover source code or underlying components, except to the extent such restrictions are prohibited by law.
          </p>
          <p style={paragraphStyle}>
            Our trademarks, logos, service marks, and branding, including the name "Blubridge" and associated marks, are our property. You may not use them without our prior written permission, except as allowed by applicable law for nominative reference.
          </p>

          {/* Section 9 */}
          <h2 style={headingStyle}>9. Acceptable use and prohibited conduct</h2>
          <p style={paragraphStyle}>
            You agree to use the Services only for lawful purposes and in accordance with these Terms, applicable laws in India, and any other laws that apply to you. You must not use the Services in a way that infringes the rights of others, interferes with the operation or security of the Services, or attempts to gain unauthorized access to systems, accounts, or data.
          </p>
          <p style={paragraphStyle}>
            Without limiting the generality of the above, you must not use the Services to create, upload, input, transmit, publish, store, or share material that is unlawful, defamatory, obscene, pornographic, paedophilic, invasive of privacy (including bodily privacy), insulting or harassing on the basis of gender, racially or ethnically objectionable, related to or encouraging money laundering or gambling, harmful to minors, or otherwise inconsistent with the laws in force in India. You must not transmit patently false and untrue information with intent to mislead or harass for financial gain or to cause injury, nor engage in conduct that threatens the unity, integrity, defence, security, or sovereignty of India or public order.
          </p>
          <p style={paragraphStyle}>
            You must not introduce malicious code, attempt to bypass usage limits, remove proprietary notices, manipulate identifiers to disguise origin, scrape the Services without permission, or use the Services for competitive analysis or benchmarking where prohibited by applicable Service Specific Terms. If you integrate the Services with third-party systems, you are responsible for ensuring that you have the necessary permissions and that your use complies with third-party terms.
          </p>

          {/* Section 10 */}
          <h2 style={headingStyle}>10. User Content, Inputs and Outputs</h2>
          <p style={paragraphStyle}>
            In the course of using the Services, you may provide text, images, audio, code, data, or other materials as inputs ("Input"). You represent and warrant that you have all rights and permissions necessary to provide the Input and that providing the Input does not violate any law or infringe any third-party rights. You remain responsible for the legality, reliability, and appropriateness of your Input.
          </p>
          <p style={paragraphStyle}>
            The Services may generate outputs such as text, code, audio, summaries, classifications, or other results ("Output"). As between you and Blubridge, you own your Input and, to the extent permitted by law, you own the Output that is generated for you. Where legal assignment is required for ownership to vest, we hereby assign to you our rights, title, and interest in the Output generated for you, subject to your compliance with these Terms and any restrictions in Service Specific Terms.
          </p>
          <p style={paragraphStyle}>
            Because automated systems can produce similar results for similar prompts, you understand that Output generated for you may be similar or identical to output generated for other users. Such similarity does not affect your ownership of your Output and does not mean that we are disclosing your confidential information. You should not include confidential or sensitive information in Input unless you have assessed the risks and the relevant Service is designed and configured for such use.
          </p>

          {/* Section 11 */}
          <h2 style={headingStyle}>11. Use of Content for research, quality, and safety</h2>
          <p style={paragraphStyle}>
            To improve the reliability, safety, and performance of our Services, we may use Content, including Input and Output, for purposes such as debugging, abuse prevention, quality measurement, evaluation, and model or system improvement. Where we do so, we will handle personal data in accordance with our Privacy Policy and applicable law. If a specific Service offers settings or contractual options to limit use of Content for training or improvement, those options will be described in the relevant Service Specific Terms or account controls.
          </p>
          <p style={paragraphStyle}>
            You understand that content moderation may be applied to Inputs and Outputs to comply with law, enforce these Terms, and reduce harms. We may refuse, remove, restrict, or disable access to certain Content or features where we reasonably believe it violates these Terms, may cause harm, or may expose Blubridge or others to legal or security risks.
          </p>

          {/* Section 12 */}
          <h2 style={headingStyle}>12. Output-related disclaimers and responsible use</h2>
          <p style={paragraphStyle}>
            Outputs are generated by automated processes and are provided for informational purposes only. They may be incomplete, inaccurate, or outdated, and may not reflect real-world facts or circumstances. You are responsible for independently evaluating Outputs before relying on them, and for using appropriate human review and safeguards for your use case.
          </p>
          <p style={paragraphStyle}>
            You must not rely on Outputs as a substitute for professional advice, including legal, medical, financial, educational, or safety-critical advice. If you use Outputs to make decisions that affect individuals or organizations, you are responsible for ensuring compliance with applicable laws, fairness obligations, and industry standards, and for providing notice where required. Blubridge does not warrant the correctness or suitability of any Output for any particular purpose.
          </p>

          {/* Section 13 */}
          <h2 style={headingStyle}>13. Privacy and data protection</h2>
          <p style={paragraphStyle}>
            Our collection and use of personal data in connection with the Services are described in our Privacy Policy. By using the Services, you acknowledge that personal data may be processed as described in the Privacy Policy. You are responsible for ensuring that you have a lawful basis to provide any personal data of others to us, and for providing any required notices or obtaining any required consents.
          </p>
          <p style={paragraphStyle}>
            Where you are an organization customer, you may control whether certain users can access features, manage workspaces, and configure settings. Administrators may have the ability to access, control, export, and delete information within an organization account, and you are responsible for your internal governance and user management.
          </p>

          {/* Section 14 */}
          <h2 style={headingStyle}>14. Hosting location, data residency, and access</h2>
          <p style={paragraphStyle}>
            The location from which your account is served may depend on your region, billing address, and technical routing at the time of sign-up. We may host or process data in India and, where necessary to provide the Services, in other locations through our infrastructure or that of our service providers. We may migrate accounts or require migration if we update regional mappings, change infrastructure providers, or respond to legal, security, or operational requirements.
          </p>
          <p style={paragraphStyle}>
            You agree not to mask or falsify information that is used to determine region, such as IP address at sign-up, when such determination is necessary for compliance, billing, or security. If we reasonably determine that your actual region differs from our records in a way that materially affects compliance, we may take appropriate action such as migrating the account, restricting features, or closing the account.
          </p>

          {/* Section 15 */}
          <h2 style={headingStyle}>15. Third-party services, integrations, and open-source software</h2>
          <p style={paragraphStyle}>
            The Services may integrate with or include third-party software, applications, or services ("Third-Party Services"). Your access to and use of Third-Party Services may require acceptance of third-party terms and privacy policies. Blubridge does not control Third-Party Services and is not responsible for their availability, functionality, content, or security. We may add, change, restrict, or remove integrations at any time, and such changes may affect how you access or use the Services.
          </p>
          <p style={paragraphStyle}>
            Certain components of the Services may include open-source software. Open-source components are licensed under their applicable license terms, and where those license terms grant you rights, those rights are in addition to the rights granted under these Terms. If there is a conflict between these Terms and an applicable open-source license, the open-source license will govern for that component.
          </p>

          {/* Section 16 */}
          <h2 style={headingStyle}>16. Service availability, maintenance, and changes</h2>
          <p style={paragraphStyle}>
            We may perform planned maintenance, upgrades, or changes that may temporarily affect availability. Where reasonably practicable, we will provide advance notice of planned downtime through service announcements or account communications. We are not responsible for unavailability caused by events outside our reasonable control, including failures of internet connectivity, third-party networks, or force majeure events.
          </p>
          <p style={paragraphStyle}>
            We may modify, suspend, or discontinue any part of the Services, including features, models, or endpoints, at any time. If you are on a paid plan and a change materially reduces core functionality, your remedies, if any, will be as described in applicable Service Specific Terms or your order form.
          </p>

          {/* Section 17 */}
          <h2 style={headingStyle}>17. Security responsibilities</h2>
          <p style={paragraphStyle}>
            We implement technical and organizational measures designed to protect information processed by the Services against accidental loss and unauthorized access, use, alteration, or disclosure. However, no system is perfectly secure. You acknowledge that security and privacy risks cannot be completely eliminated and that you provide information at your own risk to the maximum extent permitted by law.
          </p>
          <p style={paragraphStyle}>
            You are responsible for maintaining appropriate security controls for your environment, including safeguarding credentials, using strong authentication measures where available, restricting access to authorized users, and promptly applying security updates to any systems you use to connect to the Services. You must promptly notify us of any suspected vulnerability, compromise, or misuse involving the Services or your account.
          </p>

          {/* Section 18 */}
          <h2 style={headingStyle}>18. Complaints, notices, and grievance redressal</h2>
          <p style={paragraphStyle}>
            If we receive a complaint regarding your use of the Services or Content associated with your account, we may forward the complaint to the primary email address associated with your account. You agree to respond directly and promptly to the complainant where appropriate and to take reasonable steps to resolve the issue. Where legally required, we may disclose limited information to enable lawful complaints or enforcement actions, in accordance with applicable law and our Privacy Policy.
          </p>
          <p style={paragraphStyle}>
            For grievance redressal under applicable Indian law, you may contact our designated Grievance Officer. Grievance Officer: [Name]. Email: [grievance@blubridge.example]. Address: [Registered office address, India]. We aim to acknowledge grievances within 24 hours and resolve them within timelines prescribed by law, subject to the nature of the request and the information provided.
          </p>

          {/* Section 19 */}
          <h2 style={headingStyle}>19. Suspension and termination</h2>
          <p style={paragraphStyle}>
            We may suspend or terminate your access to the Services, in whole or in part, at any time if we reasonably believe that you have violated these Terms, if your use poses a security, legal, or reputational risk, if required by law or governmental request, or if necessary to prevent harm or abuse. Where reasonably practicable, we will provide notice of suspension and an opportunity to address the issue, but we may act without notice where immediate action is necessary.
          </p>
          <p style={paragraphStyle}>
            You may terminate your account or stop using the Services at any time. Termination may result in loss of access to the Services and deletion of data associated with your account, subject to applicable law, retention obligations, and any contractual terms for paid Services. After termination, provisions that by their nature should survive will continue to apply, including provisions on intellectual property, disclaimers, limitation of liability, indemnity, and dispute resolution.
          </p>

          {/* Section 20 */}
          <h2 style={headingStyle}>20. Disclaimer of warranties</h2>
          <p style={paragraphStyle}>
            To the maximum extent permitted by applicable law, the Services are provided on an "as is" and "as available" basis. We disclaim all warranties of any kind, whether express, implied, or statutory, including implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Services will be uninterrupted, timely, secure, or error-free, or that defects will be corrected.
          </p>
          <p style={paragraphStyle}>
            We do not make any representations or warranties regarding the accuracy, quality, or reliability of any Outputs or other results produced by the Services. Your use of the Services and any reliance on Outputs are at your sole risk. Some jurisdictions do not allow the exclusion of certain warranties, so some of the above exclusions may not apply to you.
          </p>

          {/* Section 21 */}
          <h2 style={headingStyle}>21. Limitation of liability</h2>
          <p style={paragraphStyle}>
            To the maximum extent permitted by applicable law, Blubridge will not be liable for any indirect, incidental, special, consequential, punitive, or exemplary damages, or for loss of profits, revenue, goodwill, business interruption, or loss of data, arising out of or in connection with your use of, or inability to use, the Services, even if we have been advised of the possibility of such damages. This limitation applies whether the claim is based on contract, tort, negligence, strict liability, or any other legal theory.
          </p>
          <p style={paragraphStyle}>
            To the maximum extent permitted by applicable law, our aggregate liability for all claims arising out of or relating to the Services will not exceed the greater of (a) the Fees paid by you for the relevant paid Service during the twelve (12) months immediately preceding the event giving rise to the claim, or (b) INR 25,000. The limitations in this section apply only to the maximum extent permitted by law and do not limit liability where such limitation is prohibited.
          </p>

          {/* Section 22 */}
          <h2 style={headingStyle}>22. Indemnity</h2>
          <p style={paragraphStyle}>
            You agree to indemnify, defend, and hold harmless Blubridge, its directors, officers, employees, contractors, and affiliates from and against any claims, demands, actions, losses, liabilities, damages, costs, and expenses (including reasonable legal fees) arising out of or related to your use of the Services, your Input, your breach of these Terms, or your violation of any law or third-party rights. This obligation will survive termination of these Terms.
          </p>

          {/* Section 23 */}
          <h2 style={headingStyle}>23. Force majeure</h2>
          <p style={paragraphStyle}>
            We will not be liable for failure or delay in performance to the extent such failure or delay is caused by circumstances beyond our reasonable control, including natural disasters, acts of government, war, terrorism, labour disputes, power failures, internet or telecommunications failures, or failures of third-party providers. We will use reasonable efforts to restore performance when the force majeure event concludes.
          </p>

          {/* Section 24 */}
          <h2 style={headingStyle}>24. Changes to these Terms</h2>
          <p style={paragraphStyle}>
            We may update these Terms from time to time to reflect changes in the Services, legal requirements, or operational practices. If we make material changes that affect your rights, we will provide notice through a service announcement, by email to your account address, or by posting an updated version on our website, and we will indicate the effective date of the updated Terms. Your continued use of the Services after the effective date constitutes acceptance of the updated Terms.
          </p>
          <p style={paragraphStyle}>
            If you do not agree to an updated version of these Terms, you must stop using the Services and, where applicable, cancel your subscription before the changes take effect.
          </p>

          {/* Section 25 */}
          <h2 style={headingStyle}>25. Assignment and subcontracting</h2>
          <p style={paragraphStyle}>
            You may not assign or transfer your rights or obligations under these Terms without our prior written consent. Any attempted assignment in violation of this provision will be null and void. We may assign these Terms or subcontract our obligations, in whole or in part, to an affiliate or third party in connection with a merger, acquisition, reorganization, or sale of assets, or for operational purposes, provided that such assignment does not materially diminish your rights under these Terms.
          </p>

          {/* Section 26 */}
          <h2 style={headingStyle}>26. Relationship of the parties</h2>
          <p style={paragraphStyle}>
            Nothing in these Terms creates a partnership, joint venture, employment, fiduciary relationship, or agency relationship between you and Blubridge. Neither party has authority to bind the other or to incur obligations on the other's behalf except as expressly stated in these Terms.
          </p>

          {/* Section 27 */}
          <h2 style={headingStyle}>27. Governing law, jurisdiction, and dispute resolution</h2>
          <p style={paragraphStyle}>
            These Terms are governed by the laws of India, without regard to conflict of laws principles. Subject to any mandatory consumer protection provisions that apply, the courts of competent jurisdiction at the place of our registered office in India will have exclusive jurisdiction over any disputes arising out of or relating to these Terms or the Services.
          </p>
          <p style={paragraphStyle}>
            You agree to resolve disputes only on an individual basis and, to the maximum extent permitted by law, waive any right to bring or participate in a class action, collective action, or representative proceeding against Blubridge.
          </p>

          {/* Section 28 */}
          <h2 style={headingStyle}>28. Electronic communications</h2>
          <p style={paragraphStyle}>
            By using the Services, you consent to receive communications from us electronically, including notices, agreements, disclosures, and service announcements. We may communicate by email, through the Service interface, or by posting notices on our website. Communications will be deemed received when sent or posted. You are responsible for keeping your contact information current and for retaining copies of communications for your records.
          </p>

          {/* Section 29 */}
          <h2 style={headingStyle}>29. Miscellaneous</h2>
          <p style={paragraphStyle}>
            These Terms constitute the entire agreement between you and Blubridge regarding the Services and supersede any prior or contemporaneous understandings, communications, or agreements, whether written or oral, relating to the subject matter. If any provision is held invalid or unenforceable, that provision will be limited to the minimum extent necessary and the remaining provisions will remain in effect. Our failure to enforce any provision of these Terms is not a waiver of our right to do so later. No waiver will be effective unless in writing and signed by an authorized representative of Blubridge. Headings are for convenience only and do not affect interpretation.
          </p>

          {/* Section 30 - Contact */}
          <section style={{
            marginTop: '48px',
            paddingTop: '32px',
            borderTop: '1px solid #e8e6e0'
          }}>
            <h2 style={{
              fontSize: '20px',
              fontWeight: '600',
              color: '#0B1F3B',
              marginBottom: '16px'
            }}>
              30. Contact
            </h2>
            <p style={paragraphStyle}>
              If you have questions about these Terms or the Services, you may contact us at:
            </p>
            <div style={{
              marginTop: '16px',
              padding: '20px',
              backgroundColor: '#F8F9FD',
              borderRadius: '8px',
              border: '1px solid #e8e6e0'
            }}>
              <p style={{
                fontSize: '15px',
                color: '#4a5568',
                marginBottom: '8px'
              }}>
                <strong style={{ color: '#0B1F3B' }}>Legal:</strong>{' '}
                <a 
                  href="mailto:legal@blubridge.com"
                  style={{
                    color: '#0B1F3B',
                    textDecoration: 'none',
                    borderBottom: '1px solid #0B1F3B'
                  }}
                >
                  legal@blubridge.com
                </a>
              </p>
              {/* <p style={{
                fontSize: '15px',
                color: '#4a5568',
                margin: 0
              }}>
                <strong style={{ color: '#0B1F3B' }}>Support:</strong>{' '}
                <a 
                  href="mailto:support@blubridge.example"
                  style={{
                    color: '#0B1F3B',
                    textDecoration: 'none',
                    borderBottom: '1px solid #0B1F3B'
                  }}
                >
                  support@blubridge.com
                </a>
              </p> */}
              <p style={{
                fontSize: '14px',
                color: '#6b7280',
                marginTop: '12px',
                marginBottom: 0
              }}>
                Please include sufficient detail for us to understand and respond to your request. If you are contacting us about a security issue, include non-sensitive technical details and do not include passwords or secrets.
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsConditions;
