import React, { useState, useEffect, useRef } from 'react';
import useDocumentTitle from '../../hooks/useDocumentTitle';
import { Link } from 'react-router-dom';
import { Button } from '../../components/ui/button';
import { ArrowRight, Plus, Minus, Server, Play } from 'lucide-react';

const Glomfjord = () => {
  const [openFaq, setOpenFaq] = useState(null);
  const heroRef = useRef(null);
  const [heroOffset, setHeroOffset] = useState(0);

  // Parallax effect for hero background
  useEffect(() => {
    const handleScroll = () => {
      if (heroRef.current) {
        const scrollY = window.scrollY;
        const heroHeight = heroRef.current.offsetHeight;
        if (scrollY < heroHeight) {
          setHeroOffset(scrollY * 0.4);
        }
      }
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const toggleFaq = (index) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  // Key Facts Data
  const keyFacts = [
    {
      value: '100%',
      title: 'Renewable Energy',
      description: 'Glomfjord operates on 100% renewable power generated by the region\'s hydropower dams.'
    },
    {
      value: '30MW',
      title: 'Power Capacity',
      description: '30MW operational capacity expandable to 60MW.'
    },
    {
      value: 'Glomfjord',
      title: 'Northern Norway',
      description: 'Located in the Arctic Circle, Glomfjord leverages the local climate for energy efficient adiabatic cooling.'
    },
    {
      value: 'Low-latency Fibre',
      title: 'Double redundant low-latency fibre',
      description: 'The data center is built directly over double redundant low-latency fibre, giving it both high speeds and reliability.'
    }
  ];

  // FAQ Data
  const faqs = [
    {
      question: "What renewable energy powers the Glomfjord data center?",
      answer: "The Glomfjord data center operates on 100% renewable energy sourced from nearby hydropower dams. The region has been generating hydroelectric power for over 100 years, providing a stable and abundant supply of clean electricity ideal for AI infrastructure."
    },
    {
      question: "What makes Glomfjord ideal for AI compute?",
      answer: "Glomfjord's Arctic location offers natural cooling advantages, reducing energy consumption. Combined with abundant renewable power, double-redundant low-latency fibre connectivity, and our optimized AI infrastructure, it provides exceptional performance and efficiency for AI workloads."
    },
    {
      question: "How does BluBrg contribute to the local community?",
      answer: "BluBrg actively invests in Glomfjord's community by funding local infrastructure, creating employment opportunities, and exploring innovative heat reuse projects such as heating the local community swimming pool with waste heat from the data center."
    },
    {
      question: "What compute capacity is available at Glomfjord?",
      answer: "Glomfjord currently operates at 30MW capacity with expansion potential to 60MW. We offer GPU Nodes, Training Clusters, Inference Services, Fine-tuning, and Serverless compute options all powered by 100% renewable energy."
    }
  ];

  // Infrastructure tools
  const infrastructureTools = [
    'LLM Library',
    'Job Management',
    'Container Orchestration',
    'Optimised Libraries',
    'Pre-configured Software',
    'Pre-configured Infrastructure'
  ];

  useDocumentTitle('Glomfjord AI Data Centre | BluBrg');

  return (
    <div className="min-h-screen bg-[#F3F6E8] font-['DM_Sans']">      {/* SECTION 1: Hero Section with Glomfjord Data Center Background */}
      <section ref={heroRef} className="relative min-h-[650px] flex items-center overflow-hidden">
        {/* Background Image with Parallax */}
        <div 
          className="absolute inset-0 bg-cover bg-center transition-transform duration-100"
          style={{
            backgroundImage: `url('https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1920&q=80')`,
            transform: `translateY(${heroOffset}px) scale(1.1)`
          }}
        />
        
        {/* Alternate background for Nordic fjord landscape */}
        <div 
          className="absolute inset-0 bg-cover bg-center"
          style={{
            backgroundImage: `url('https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1920&q=80')`,
            transform: `translateY(${heroOffset * 0.5}px) scale(1.1)`
          }}
        />
        
        {/* Dark Overlay */}
        <div className="absolute inset-0 bg-gradient-to-r from-black/80 via-black/60 to-black/40" />
        
        <div className="container-custom relative z-10">
          <div className="max-w-3xl" style={{ animation: 'fadeInUp 1s ease-out' }}>
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-[#0B1F3B]/20 rounded-full border border-blue-600/30 mb-6">
              <span className="text-[#328CC1] text-sm font-medium">AI DATA CENTER</span>
            </div>
            
            <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold leading-tight mb-6 text-white" style={{ animation: 'fadeInUp 1s ease-out 0.2s both' }}>
              Glomfjord, Norway
            </h1>
            
            <p className="text-white/90 text-lg md:text-xl max-w-2xl leading-relaxed mb-8" style={{ animation: 'fadeInUp 1s ease-out 0.4s both' }}>
Our Glomfjord AI data centre, positioned in northern Norway, runs entirely on renewable energy and integrates cutting-edge AI infrastructure to deliver industry-leading efficiency without compromising performance. 
            </p>
            
            <div className="flex flex-wrap gap-4" style={{ animation: 'fadeInUp 1s ease-out 0.6s both' }}>
              <Link to="/contact/sales">
                <Button className="bg-white text-black hover:bg-gray-100 px-8 py-3 rounded font-medium">
                  Get Started
                </Button>
              </Link>
               <Link to="/contact/sales" className="inline-flex items-center gap-2 text-white hover:text-blue-300 transition-colors font-medium">
                Contact Sales <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
          </div>
        </div>

        <style>{`
          @keyframes fadeInUp {
            from { opacity: 0; transform: translateY(30px); }
            to { opacity: 1; transform: translateY(0); }
          }
        `}</style>
      </section>

      {/* SECTION 2: Intro Section */}
      <section className="py-20 bg-[#F3F6E8]">
        <div className="container-custom">
          <div className="max-w-6xl">
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-6 text-[#0B1F3B]">
              The data center on the edge of<br />the Arctic Circle
            </h2>
            <br></br>
            <p className="text-[#243447] text-lg leading-relaxed">
             Situated just above the Arctic Circle, the Glomfjord facility demonstrates how future AI growth can coexist with local development. The location offers unique environmental and logistical advantages that support sustainable, high-capacity compute operations. 
            </p>
            <br></br>
             <p className="text-[#243447] text-lg leading-relaxed">
             Blubrg is also committed to the local community by investing in infrastructure, creating job opportunities, and exploring innovative ways to reuse waste heat, such as heating local facilities. 
            </p>
          </div>
        </div>
      </section>

      {/* SECTION 3: Embedded Video Section */}
      {/* <section className="py-16 bg-[#EEF2DC]">
        <div className="container-custom">
          <h2 className="text-3xl md:text-4xl font-bold mb-8">Transforming Tomorrow</h2>
          
         
          <div className="max-w-4xl">
            <div className="relative bg-slate-900/50 rounded-xl border border-[#D6DEC3] overflow-hidden aspect-video mb-6">
            
              <div className="absolute inset-0 bg-gradient-to-br from-slate-800 to-slate-900 flex items-center justify-center">
                <div className="text-center">
                  <div className="w-20 h-20 rounded-full bg-red-600/80 mx-auto mb-4 flex items-center justify-center cursor-pointer hover:bg-red-600 transition-colors">
                    <Play className="w-8 h-8 text-white ml-1" />
                  </div>
                  <p className="text-[#243447] text-sm">BBC Storyworks - Transforming Tomorrow</p>
                </div>
              </div>
              
              
              <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-4">
                <div className="flex items-center gap-4">
                  <div className="w-full bg-gray-700/50 h-1 rounded-full">
                    <div className="w-1/3 bg-red-600 h-1 rounded-full" />
                  </div>
                </div>
              </div>
            </div>
            
            <p className="text-[#243447] text-sm leading-relaxed">
              BluBrg features in the brand-new online series 'Transforming Tomorrow' – a highlight episode takes you inside our data center in Glomfjord, Norway where we're building the future. You'll hear from our leadership team as they share our vision for how the way we build today can redefine how we live tomorrow. The series is produced by BBC Storyworks Commercial Productions.
            </p>
          </div>
        </div>
      </section> */}

      {/* SECTION 4: About Section */}
      <section className="py-20 bg-[#F3F6E8]">
        <div className="container-custom">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-3xl md:text-4xl font-bold mb-6 text-[#0B1F3B]">About</h2>
              <div className="space-y-4 text-[#243447] leading-relaxed">
                <p>
                  Glomfjord is a small industrial town of 1000 people in the North of Norway, just above the Arctic Circle. The industry in the town is based around the 120MW hydro power plant that was built at the end of the fjord over 100 years ago.
                </p>
                <p>
                  This unique location is perfectly suited to High Performance Computing (HPC) and the computational requirements of AI—it's cold, well connected, and there is a stable oversupply of renewable energy.
                </p>
                <p>
                  BluBrg is actively investing in the community. We are putting money towards local infrastructure, creating jobs, and looking to reuse the data centers generated heat for things such as warming the local community swimming pool.
                </p>
              </div>
            </div>
            
            {/* About Image */}
            <div className="relative">
              <div className="bg-slate-900/50 rounded-xl border border-[#D6DEC3]/30 overflow-hidden aspect-video">
                <img 
                  src="https://images.unsplash.com/photo-1520769669658-f07657f5a307?w=800&q=80" 
                  alt="Glomfjord Data Center aerial view"
                  className="w-full h-full object-cover"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* SECTION 5: Key Facts Section */}
      <section className="py-20 bg-[#EEF2DC]">
        <div className="container-custom">
          <h2 className="text-3xl md:text-4xl font-bold mb-12">Key Facts</h2>
          
          <div className="grid md:grid-cols-4 gap-8">
            {keyFacts.map((fact, i) => (
              <div key={i}>
                <div className="text-3xl md:text-4xl font-bold text-[#0B1F3B] mb-2">{fact.value}</div>
                <div className="text-[#0B1F3B] font-semibold mb-2">{fact.title}</div>
                <p className="text-[#243447] text-sm leading-relaxed">{fact.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* SECTION 6: Power Supply Section */}
      <section className="py-20 bg-[#F3F6E8]">
        <div className="container-custom">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            {/* Power Supply Image */}
            <div className="relative">
              <div className="bg-slate-900/50 rounded-xl border border-[#D6DEC3]/30 overflow-hidden aspect-video">
                <img 
                  src="https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80" 
                  alt="Hydroelectric dam"
                  className="w-full h-full object-cover"
                />
              </div>
            </div>
            
            <div>
              <h2 className="text-3xl md:text-4xl font-bold mb-6 text-[#0B1F3B]">Power Supply</h2>
              <div className="space-y-4 text-[#243447] leading-relaxed">
                <p>
                  To meet the demand for AI infrastructure, BluBrg operates data centers in regions with a stable oversupply of renewable power. This strategy avoids straining the local grid and prevents driving up energy prices for residents.
                </p>
                <p>
                  Glomfjord, with its hydropower dams, boasts an abundance of renewable energy. This results in a stable supply of excess renewable power, ideal for supporting AI infrastructure needs.
                </p>
                <p>
                  BluBrg's AI data center is powered entirely by this renewable energy, ensuring that we provide sustainable and efficient AI compute.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* SECTION 7: AI Services/Compute Section */}
      <section className="py-20 bg-[#EEF2DC]">
        <div className="container-custom">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-3xl md:text-4xl font-bold mb-6 text-[#0B1F3B]">
                Get access to a fully<br />integrated suite of AI<br />services and compute
              </h2>
              <p className="text-[#243447] mb-6 leading-relaxed">
                Reduce costs, grow revenue, and run your AI workloads more efficiently on a fully integrated platform. Whether you're using <Link to="/" className="text-[#328CC1] hover:underline">BluBrg</Link>'s built-in AI/ML tools or your own, our platform is designed to simplify the journey from development to production.
              </p>
            </div>
            
            {/* Infrastructure Diagram */}
            <div className="bg-slate-900/30 rounded-xl border border-[#D6DEC3]/30 p-6">
              <div className="grid grid-cols-2 gap-3 mb-4">
                <div className="bg-[#EEF2DC] rounded-lg p-3 text-center border border-[#D6DEC3]/30">
                  <span className="text-sm text-[#243447]">Serverless</span>
                </div>
                <div className="bg-[#EEF2DC] rounded-lg p-3 text-center border border-[#D6DEC3]/30">
                  <span className="text-sm text-[#243447]">Marketplace</span>
                </div>
              </div>
              
              <div className="grid grid-cols-2 gap-3 mb-4">
                <div className="bg-[#0B1F3B]/20 rounded-lg p-3 text-center border border-blue-500/30">
                  <span className="text-sm text-blue-300">Inference</span>
                </div>
                <div className="bg-[#0B1F3B]/20 rounded-lg p-3 text-center border border-blue-500/30">
                  <span className="text-sm text-blue-300">Training</span>
                </div>
              </div>
              
              <div className="grid grid-cols-2 gap-2 mb-4">
                {infrastructureTools.map((tool, i) => (
                  <div key={i} className="bg-slate-800/30 rounded-lg p-2 text-center border border-[#D6DEC3]/20">
                    <span className="text-xs text-[#243447]">{tool}</span>
                  </div>
                ))}
              </div>
              
              <div className="bg-[#EEF2DC] rounded-lg p-3 text-center border border-[#D6DEC3]/30 mb-4">
                <span className="text-sm text-[#243447]">GPU nodes</span>
              </div>
              
              {/* Data Center Badge */}
              <div className="bg-slate-900 rounded-lg p-4 border border-[#D6DEC3]">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 bg-[#0B1F3B]/20 rounded-lg flex items-center justify-center">
                    <Server className="w-4 h-4 text-[#328CC1]" />
                  </div>
                  <div>
                    <div className="text-[#0B1F3B] text-sm font-medium">BluBrg's Data centers</div>
                    <div className="text-xs text-[#5B6B7A]">Powered by renewable energy</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      
      {/* SECTION 9: FAQ Section */}
      <section className="py-20 bg-[#F3F6E8]">
        <div className="container-custom max-w-4xl">
          <h2 className="text-3xl md:text-4xl font-bold mb-10">FAQs</h2>
          
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div 
                key={index} 
                className="border-b border-[#D6DEC3] pb-4"
              >
                <button
                  onClick={() => toggleFaq(index)}
                  className="w-full flex items-center justify-between text-left py-3 group"
                >
                  <span className="text-[#0B1F3B] text-lg pr-4">{faq.question}</span>
                  <span className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center transition-all duration-300 ${openFaq === index ? 'bg-[#0B1F3B] rotate-180' : 'bg-[#0B1F3B]/80'}`}>
                    {openFaq === index ? (
                      <Minus className="w-4 h-4 text-white" />
                    ) : (
                      <Plus className="w-4 h-4 text-white" />
                    )}
                  </span>
                </button>
                
                <div className={`overflow-hidden transition-all duration-300 ${openFaq === index ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'}`}>
                  <p className="text-[#243447] pb-4 pr-12">{faq.answer}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

{/* SECTION 8: Final CTA Section */}
      <section className="py-16 bg-gradient-to-r from-blue-600 to-blue-700">
        <div className="container-custom text-center">
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-8">
            Access thousands of GPUs tailored to your requirements.
          </h2>
          
          <div className="flex flex-wrap justify-center gap-4">
            <Link to="/contact/sales">
              <Button className="bg-white text-[#0B1F3B] hover:bg-gray-100 px-8 py-3 rounded font-medium">
                Reserve GPUs
              </Button>
            </Link>
            <Link to="/contact/sales" className="flex items-center gap-2 text-white hover:text-blue-100 transition-colors font-medium px-6 py-0">
              Contact Sales <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>


    </div>
  );
};

export default Glomfjord;
